name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy:
    name: Déployer via FTP
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Déployer via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./ 
          server-dir: / 
          port: ${{ secrets.PORT || 21 }}
          protocol: ftp
          dry-run: false