name: CI/CD Pipeline Frontend

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Frontend:
    name: Déployer via FTP (Frontend)
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4


      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Installer les dépendances (npm install)
        run: npm install

      - name: Builder le projet (npm run build)
        run: npm run build
      # --- FIN DES AJOUTS ---

      - name: Déployer via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./dist/
          server-dir: ./public_html/